### ISSUE TITLE
1.16.1 - Compatibility

### ISSUE THREAD

**Issue by wazoooo** [KaptainWutax/SeedCracker#52] opened 2020-06-26 17:17 UTC
When will you release a 1.16.1 version for SeedCracker?

**Comment by Neffc** [comment] 2020-06-26 17:42
Duplicate of #50 and #51.

**Comment by hube12** [comment] 2020-06-28 22:38
Hi, you mentionned 1.16.X, due to high demand this feature will come in the next few days/months.The less issues, the faster the dev can work. Enjoy a cup of tea 🍵 while waiting !

**Closed** 2020-06-30 14:27 UTC
Labels: annoying, question
